#!/usr/bin/env python3
"""Static audit of the luci-theme-footstrap CSS sources (the styles/ tree, one dir per
cascade layer; cascade.css is generated by build-css.sh and not read here — docs/css.md).

Checks, in print order. The "why" of each sits on the function that implements it:
  1. balance()            bracket balance — a smoke test for a truncated file. CSS only;
                          see the note in main() for why the JS check was dropped.
  2. audit_vars()         var() reads of a property nobody defines: the declaration is
                          dropped silently, so a shadow or colour just vanishes.
  3. (in main)            !important outside the files allowed to carry it — BANG_OK.
  4. audit_shadowed()     one property set twice on one selector in one layer.
  5. audit_export_reads() reads of the outward `--*-color-*` tier from inside the theme.
  6. audit_base_dead()    base declarations a later layer repaints: the removable ones,
                          and the absorption backlog that must NOT be deleted.
  7. base_hardcoded()     colour literals in styles/base — a literal cannot follow a
                          palette or dark mode.

No dependencies, any python3; --strict turns the report into a CI gate. A static audit
cannot see the cascade: for "did this change a computed style?" use cssdiff.py here.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1] / "luci-theme-footstrap"
STYLES = ROOT / "styles"
BASE = STYLES / "base"
# The only files allowed an !important, and each for a reason no cascade layer covers.
# This same list lives in .stylelintrc.json (the declaration-no-important:null override);
# tools/bang-ok.mjs (npm run bang-ok) holds the two copies to each other, since Python and a
# JSON config cannot share an import.
# 90-responsive/20-overview outrank an inline style= written by ui.js or
# luci-mod-status's 29_ports.js; 45-misc outranks the inline style='width:100%' the
# realtime graphs write on the box they draw into (their drawing is sized from #view,
# so the card's gutter clips it unless the box is widened back); styles/base carries
# widget-internal layout (.cbi-dropdown) and the .left/.right/.center forcing
# utilities; 95-a11y-media needs it because the flag INVERTS the layer order — the
# only way one rule can stop animations declared in base as well as in theme.
BANG_OK = ({"90-responsive.css", "20-overview.css", "95-a11y-media.css", "45-misc.css",
            # 65-dropdown carries the widget's `ul` margin flag: ui.js writes `margin` INLINE on
            # an open list, and only an author !important outranks an inline style. It moved here
            # with the machinery absorbed from base/80-dropdown.css (deleted).
            "65-dropdown.css"}
           | {p.name for p in (STYLES / "base").glob("*.css")})

# var()s legitimately not defined inside styles/: --zone-color-rgb is written inline on a zone
# badge by luci-mod-network — the only --*-rgb that may exist (the theme's own RGB and HSL bridges
# were removed; see 02-tokens.css).
VAR_ALLOW = {"--zone-color-rgb"}

def _strip_for_balance(s):
    """Drop comments and quoted strings before counting brackets.

    Counting raw punishes the dense comments this project asks for: one explaining a
    hazard ("`(` IS on the allow-list") carries a lone paren, and the file reads as
    unbalanced. This is only a smoke test for a truncated file, which stays obvious
    once comments and strings are gone.
    """
    out, i, n = [], 0, len(s)
    while i < n:
        c = s[i]
        if c == "/" and i + 1 < n and s[i + 1] == "*":          # /* block comment */
            j = s.find("*/", i + 2)
            i = n if j < 0 else j + 2
            continue
        if c == "/" and i + 1 < n and s[i + 1] == "/":          # // line comment
            j = s.find("\n", i)
            i = n if j < 0 else j
            continue
        if c in "\"'`":                                          # quoted string
            q, i = c, i + 1
            while i < n:
                if s[i] == "\\":
                    i += 2
                    continue
                if s[i] == q:
                    i += 1
                    break
                i += 1
            continue
        out.append(c)
        i += 1
    return "".join(out)

def balance(path):
    s = _strip_for_balance(path.read_text(encoding="utf-8"))
    bad = [f"{a}{b} {s.count(a)}/{s.count(b)}"
           for a, b in [("{", "}"), ("(", ")"), ("[", "]")] if s.count(a) != s.count(b)]
    return bad

def audit_vars(s):
    # Comments first: a comment quotes the code it explains — 02-tokens.css spells the
    # removed bridge out as `rgba(var(--x), .3)` — and scanning raw turns that prose into
    # a phantom "used but not defined".
    s = _strip_comments(s)
    defined = set(re.findall(r"(--[a-zA-Z0-9-]+)\s*:", s))
    used = set(re.findall(r"var\((--[a-zA-Z0-9-]+)", s))
    return sorted(u for u in (used - defined) if u not in VAR_ALLOW)

def base_hardcoded(lines):
    sel, out = "", []
    for i, l in enumerate(lines):
        st = l.strip()
        if st.endswith("{"):
            sel = st[:-1].strip()
        if not st.startswith("--") and "--" not in l.split(":")[0]:
            # a real literal = #hex, or a colour function whose first arg is a number
            # (not a var()); black/white alpha overlays are ignored.
            after_var = re.sub(r"var\([^()]*\)", "", l)
            lit = re.search(r"#[0-9a-fA-F]{3,8}\b", after_var)
            func = re.search(r"[rh]sla?\(\s*(\d[\d.]*)", after_var)
            if func and re.match(r"(0\s*,\s*0\s*,\s*0|255\s*,\s*255\s*,\s*255)",
                                 after_var[func.start():].split("(", 1)[1].lstrip()):
                func = None
            if lit or func:
                out.append((i + 1, sel[:46], st[:80]))
    return out

# --- rule parsing (enough CSS to spot duplicate selectors; no nesting beyond
# --- @layer / @media / @supports / @container, which is all this tree uses)
def _strip_comments(src):
    """Remove comments but PRESERVE the line count.

    rules() derives every `file:line` it reports from this stripped copy. Deleting a
    comment along with its newlines shifted every reported line UP by the number of
    comment lines above the rule — in a tree whose comments outweigh its code, a big
    shift (`30-forms.css:336` really lived at :353, `95-luci.css:304` at :319), and a
    finding pointing at the wrong line gets "fixed" in the wrong rule. Newlines are
    whitespace to the parser, so substituting them in place costs nothing.
    """
    out, i = [], 0
    while i < len(src):
        j = src.find("/*", i)
        if j < 0:
            out.append(src[i:]); break
        out.append(src[i:j])
        k = src.find("*/", j + 2)
        if k < 0: break
        out.append("\n" * src.count("\n", j, k + 2))
        i = k + 2
    return "".join(out)

def _split_selectors(head):
    """split on top-level commas only — :is()/:not() may contain their own"""
    out, depth, cur = [], 0, ""
    for ch in head:
        if ch == "(": depth += 1
        elif ch == ")": depth -= 1
        if ch == "," and depth == 0:
            if cur.strip(): out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip(): out.append(cur.strip())
    return out

def rules(path):
    """yield (line, layer, context, selector, [(prop, value)…]) for one file"""
    src = path.read_text(encoding="utf-8")
    s = _strip_comments(src)
    stack, buf, i = [], "", 0
    while i < len(s):
        c = s[i]
        if c == "{":
            head, buf = buf.strip(), ""
            if head.startswith("@"):
                stack.append(head); i += 1; continue
            depth, j = 1, i + 1
            while j < len(s) and depth:
                depth += (s[j] == "{") - (s[j] == "}")
                j += 1
            body, line = s[i + 1:j - 1], s.count("\n", 0, i) + 1
            layer = next((h.split()[1] for h in stack if h.startswith("@layer ")), "")
            ctx = " ".join(h for h in stack if not h.startswith("@layer"))
            if not re.fullmatch(r"[\d.%,\s]+|from|to", head):   # skip @keyframes stops
                decls = []
                for d in body.split(";"):
                    d = d.strip()
                    if d and ":" in d and not d.startswith("--"):
                        prop, val = d.split(":", 1)
                        decls.append((prop.strip(), val.strip()))
                sels = _split_selectors(head)
                for sel in sels:
                    yield line, layer, ctx, sel, decls, len(sels)
            i = j; continue
        if c == "}":
            if stack: stack.pop()
            buf = ""; i += 1; continue
        buf += c; i += 1

def audit_shadowed(css):
    """Same selector + layer + at-rule context, same property set twice: the earlier
    declaration is dead. theme/page only — base re-states properties on purpose (the
    reset sets `input { font-size: 100% }`, forms then sets 13px).

    Skipped when the earlier rule carried MORE selectors — the group-then-refine idiom
    (`input…, textarea { min-height: 38px }` then `textarea { min-height: 84px }`),
    where the first still works for the rest of the group. What we hunt is the reverse:
    a rule appended at the bottom restating a selector already styled above, which is
    how a stylesheet turns into a changelog."""
    seen, out = {}, []
    for p in css:
        for line, layer, ctx, sel, decls, nsel in rules(p):
            if layer not in ("theme", "page"):
                continue
            for prop, val in decls:
                k = (layer, ctx, sel, prop)
                if k in seen:
                    pf, pl, pv, pn = seen[k]
                    if pn <= nsel:
                        out.append((sel, prop, pf, pl, pv, p.name, line, val))
                seen[k] = (p.name, line, val, nsel)
    return out

# The export tier: LuCI's conventional theme variable names, DEFINED in 02-tokens.css
# from the private --fs-* and read by nobody inside the theme. Element-scoped locals
# that merely end in -color (--bd-color, --fg-color, --on-color, --focus-color, pre's
# --border-color) are not the bridge — declared inside the rule that reads them, so a
# foreign :root cannot hijack them.
EXPORT_RE = re.compile(r"var\(\s*(--(?:background|text|border|primary|error|success|warn)-color-[a-z]+"
                       r"|--on-(?:primary|error|success|warn)-color)\s*[,)]")

def audit_export_reads(css):
    """Reads of the export tier from inside styles/.

    The bridge points OUTWARD. A third-party luci-app-* declaring one of these names on
    :root — unlayered, so above every layer — silently repaints any theme rule that
    reads it. base used to read them 158 times, which made the most conventional names
    (--text-color-high &c.) the widest hole we had. Read the --fs-* token instead.
    """
    out = []
    for p in css:
        for i, line in enumerate(_strip_comments(p.read_text(encoding="utf-8")).split("\n"), 1):
            for m in EXPORT_RE.finditer(line):
                out.append((p.name, i, m.group(1), line.strip()[:60]))
    return out

def _norm(sel):
    return re.sub(r"\s+", " ", sel).strip()

def audit_base_dead(css):
    """Base declarations that a later layer repaints on an identical selector.

    theme/page beat base regardless of specificity, so these are unreachable — but
    deletability is decided by the whole selector GROUP, not the one selector. Base
    groups upstream widgets together (`.cbi-button-positive, .cbi-button-fieldadd,
    .cbi-button-add, .cbi-button-save { border-color: var(--on-color) }`) and theme
    often repaints only the first: dead for it, fully alive for the other three.
    Deleting the rule because it "looks overridden" un-themes three widgets no shipped
    LuCI page renders but a third-party luci-app-* does — the coverage contract in
    docs/conventions.md. So only an all-repainted group is reported as removable; a mixed one is
    backlog, and absorbing it means writing the uncovered selectors into `theme` first,
    never deleting here. Matching is deliberately conservative (identical selectors
    only): a wrong superset matcher would un-theme someone's app.
    """
    later = {}
    for p in css:
        for line, layer, ctx, sel, decls, nsel in rules(p):
            if layer in ("theme", "page"):
                later.setdefault((ctx, _norm(sel)), set()).update(pr for pr, _ in decls)

    groups = {}   # one entry per base RULE, keyed by where it starts
    for p in css:
        for line, layer, ctx, sel, decls, nsel in rules(p):
            if layer != "base":
                continue
            g = groups.setdefault((p.name, line, ctx), {"sels": [], "decls": decls})
            g["sels"].append(_norm(sel))

    safe, backlog = [], []
    for (name, line, ctx), g in sorted(groups.items()):
        for prop, val in g["decls"]:
            # an !important in base OUTRANKS one in theme (the flag inverts the layer
            # order), so it is not dead at all
            if "!important" in val:
                continue
            cov = [prop in later.get((ctx, s), ()) for s in g["sels"]]
            if not cov:
                continue
            if all(cov):
                safe.append((name, line, ", ".join(g["sels"]), prop, val))
            elif any(cov):
                backlog.append((name, line, prop,
                                [s for s, c in zip(g["sels"], cov) if not c]))
    return safe, backlog

def sources():
    """Every source file, in the order build-css.sh concatenates them."""
    return (sorted(STYLES.glob("*.css"))
            + sorted((STYLES / "base").glob("*.css"))
            + sorted((STYLES / "theme").glob("*.css"))
            + sorted((STYLES / "pages").glob("*.css")))

def report(title, lines, empty="none", *hints):
    """Print one section and return its finding count.

    Every section is header -> items -> count -> hint, and seven hand-written copies had already
    drifted: one printed its header with no leading blank line, and the empty case was spelled
    three ways. The real hazard is the count — a new section whose author forgets `findings +=`
    is silently non-gating under --strict, which is the one thing this script is for. Returning
    the number makes forgetting it impossible.
    """
    print(f"\n== {title} ==")
    if not lines:
        print(f"  {empty}")
        return 0
    for l in lines:
        print("  " + l)
    for h in hints:
        print("  " + h)
    return len(lines)

def main():
    if not BASE.is_dir():
        sys.exit(f"not found: {BASE}")
    strict = "--strict" in sys.argv   # CI gate: exit non-zero if anything is reported
    findings = 0
    css = sources()
    s = "\n".join(p.read_text(encoding="utf-8") for p in css)

    # CSS only, deliberately: this used to count brackets in the JS too. Raw counting
    # punished dense comments, and counting after a hand-rolled strip was worse — that
    # stripper read the `//` inside `.replace(/\//g, '.')` as a line comment and ate the
    # rest of the line, i.e. the exact jsmin bug class it was meant to find. A tool that
    # cannot lex JS has no business counting its brackets. eslint parses the JS for real
    # (CI `lint`) and tools/jsmin-verify.mjs proves the minified output is
    # token-identical; those are the authorities, this was a guess that cried wolf.
    findings += report("balance (CSS)",
        [f"BAD {p.relative_to(ROOT)}: {', '.join(b)}" for p in css if (b := balance(p))],
        "ok (all balanced)")

    miss = audit_vars(s)
    findings += report("css vars used but not defined",
        [f"{m}  (x{s.count('var(' + m)})" for m in miss])

    stray = [(p.name, i, l.strip()[:70])
             for p in css if p.name not in BANG_OK
             for i, l in enumerate(p.read_text(encoding="utf-8").split("\n"), 1)
             # a flag that terminates a declaration; prose in a comment does not
             if re.search(r"!important\s*[;}]", l)]
    findings += report("!important outside the files allowed to carry it",
        [f"{name}:{ln}  {txt}" for name, ln, txt in stray], "none",
        "-> move the rule to a later layer, or merge it with its twin")

    sh = audit_shadowed(css)
    findings += report("declarations shadowed within a layer (theme/page)",
        [f"{sel} {{ {prop} }}  {pf}:{pl} {pv!r} -> {f}:{ln} {v!r}"
         + ("  SAME VALUE" if pv == v else "")
         for sel, prop, pf, pl, pv, f, ln, v in sh], "none",
        f"({len(sh)} dead) -> edit the first rule instead of appending a second",
        "   (group-then-refine, e.g. a shared input rule narrowed for textarea, is not reported)")

    ex = audit_export_reads(css)
    findings += report("reads of the EXPORT tier (--*-color-*) from inside the theme",
        [f"{name}:{ln:<4} {var:24} {txt}" for name, ln, var, txt in ex],
        "none (the bridge points outward only)",
        f"({len(ex)}) -> read the --fs-* token it aliases. A third-party luci-app-* can",
        "   declare these names on :root, unlayered, and repaint the theme silently.")

    safe, backlog = audit_base_dead(css)
    findings += report("base declarations a later layer repaints on the SAME selector",
        [f"{name}:{ln:<4} {sel[:56]}  {{ {prop}: {val[:34]} }}" for name, ln, sel, prop, val in safe],
        "none removable",
        f"({len(safe)} dead) -> every selector of the rule is repainted by theme/page,",
        "   so deleting these changes no rendered style (prove it with cssdiff.py)")
    # NOT a report() section: it re-groups by selector rather than listing findings, and it is
    # deliberately NOT counted — the backlog is the to-do list, not a failure.
    if backlog:
        print(f"\n  -- absorption backlog: {len(backlog)} declaration(s) where only PART of the")
        print("     selector group is repainted. DO NOT DELETE: the members listed below are")
        print("     styled by base alone, and third-party luci-app-* packages emit them.")
        seen_sel = {}
        for name, ln, prop, missing in backlog:
            for m in missing:
                seen_sel.setdefault(m, set()).add(prop)
        for m, props in sorted(seen_sel.items()):
            print(f"       {m[:58]:58} base-only for: {', '.join(sorted(props))[:40]}")

    hc = [(p.name, ln, sel, txt)
          for p in sorted(BASE.glob("*.css"))
          for ln, sel, txt in base_hardcoded(p.read_text(encoding="utf-8").split("\n"))]
    findings += report("hardcoded colors in styles/base (candidates to tokenize)",
        [f"{name}:{ln:<4} [{sel}] {txt}" for name, ln, sel, txt in hc], "none",
        f"({len(hc)} lines)")

    # A plain run is a report and always exits 0 (fine for a human, useless as a gate);
    # --strict fails the build on anything reported.
    if strict and findings:
        print(f"\nFAIL: {findings} finding(s) — see above", file=sys.stderr)
        return 1
    return 0

if __name__ == "__main__":
    sys.exit(main() or 0)
